# Generated by Django 6.0.6 on 2026-07-02 01:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliotecas', to='core.videojuego'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='puntuacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='resena',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resena',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.videojuego'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegos', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='desarrolladora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegos', to='core.desarrolladora'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='plataformas',
            field=models.ManyToManyField(related_name='videojuegos', to='core.plataforma'),
        ),
        migrations.AlterUniqueTogether(
            name='biblioteca',
            unique_together={('usuario', 'videojuego')},
        ),
    ]
